services:
  workspace:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bookworm
    command: sleep infinity
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    volumes:
      - .:/workspaces/detectiv:cached
