from importlib.metadata import version

from detectiv.data import TemporalSplit, TimeSeries
from detectiv.datasets import (
    Dataset,
    ImageDataset,
    ImageFolderWriter,
    ImageFormat,
    ImageOutputConfig,
    ImageShape,
    ImageSource,
    TemporalBoundary,
    TemporalSplitter,
    TimeSeriesDataset,
    TSBADCsvLoader,
)
from detectiv.ts2i import (
    MSM,
    PCA,
    Channelization,
    FixedProjectionStrategy,
    Identity,
    ImagePreparation,
    ProjectionScheme,
    ProjectionStrategy,
    RandomNoise,
    TransformationInput,
    TS2ITransformation,
)
from detectiv.windowing import (
    SplitPart,
    SplitWindowing,
    TailPolicy,
    WindowBatch,
    Windower,
    WindowLabelingStrategy,
    WindowMode,
    WindowReference,
    WindowSpec,
)

__version__ = version("detectiv")

__all__ = [
    "MSM",
    "PCA",
    "Channelization",
    "Dataset",
    "FixedProjectionStrategy",
    "Identity",
    "ImageDataset",
    "ImageFolderWriter",
    "ImageFormat",
    "ImageOutputConfig",
    "ImagePreparation",
    "ImageShape",
    "ImageSource",
    "ProjectionScheme",
    "ProjectionStrategy",
    "RandomNoise",
    "SplitPart",
    "SplitWindowing",
    "TS2ITransformation",
    "TSBADCsvLoader",
    "TailPolicy",
    "TemporalBoundary",
    "TemporalSplit",
    "TemporalSplitter",
    "TimeSeries",
    "TimeSeriesDataset",
    "TransformationInput",
    "WindowBatch",
    "WindowLabelingStrategy",
    "WindowMode",
    "WindowReference",
    "WindowSpec",
    "Windower",
    "__version__",
]
